version: '3.8'

services:
  postgresql:
    image: postgres:13.22-alpine3.22
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=board_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:8.2.0-alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - dev

  elasticsearch:
    image: elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=test
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - dev

  kibana:
    image: kibana:9.1.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - dev

  rabbitmq:
    image: rabbitmq:4.1.3-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - dev

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  es_data:
    driver: local
  kibana_data:
    driver: local

networks:
  dev:
    driver: bridge
